# Generated by Django 5.2.1 on 2025-06-30 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('check_in', models.TimeField(default=django.utils.timezone.now)),
                ('check_out', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
